apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo
  labels:
    app: app-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-demo
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      containers:
        - name: app-demo
          image: docker.io/kennethreitz/httpbin
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: 8080
         
